"""deleted table synonyms

Revision ID: 4769b8b438cb
Revises: 51a2f113d6f3
Create Date: 2026-02-14 18:35:16.433796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4769b8b438cb'
down_revision: Union[str, Sequence[str], None] = '51a2f113d6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('synonyms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synonyms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('synonyms_skill_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('synonyms_pkey')),
    sa.UniqueConstraint('name', name=op.f('synonyms_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
