"""fix

Revision ID: 6ff2a6c7f671
Revises: 428ebb490bdd
Create Date: 2026-03-23 18:42:58.309110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff2a6c7f671'
down_revision: Union[str, Sequence[str], None] = '428ebb490bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('experience', sa.String(), nullable=True))
    op.drop_column('vacancies', 'expirience')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('expirience', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('vacancies', 'experience')
    # ### end Alembic commands ###
